<?php

/** Generated by Latte 3.0.23 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: D:\NettePHPFramework\nette-blog\app\Modules\Front\Presenters/templates/Home/default.latte */
final class Template_95fab6a63e extends Latte\Runtime\Template
{
	public const Source = 'D:\\NettePHPFramework\\nette-blog\\app\\Modules\\Front\\Presenters/templates/Home/default.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}
	}
}
